language: ruby
rvm:
  - "1.9.3"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
before_script:
  - psql -c 'create database test_tond' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
branches:
  only:
    - master
